on:
  release:
    types: [created]

jobs:
  push_image:
    env:
      IMAGE_TAG: jandelgado/openwrt-imagecompiler
    runs-on: ubuntu-latest
    name: push image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test build Docker image
        run: ./builder.sh build-docker-image --skip-sudo
      - name: push image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USER}}" --password-stdin docker.io
          docker tag ${IMAGE_TAG} ${IMAGE_TAG}:${GITHUB_SHA}
          docker tag ${IMAGE_TAG}:${GITHUB_SHA} ${IMAGE_TAG}:${TAG}
          docker tag ${IMAGE_TAG}:${GITHUB_SHA} ${IMAGE_TAG}:latest
          docker push ${IMAGE_TAG}:${GITHUB_SHA}
          docker push ${IMAGE_TAG}:${TAG}
          docker push ${IMAGE_TAG}:latest

