name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        run: shellcheck builder.sh example/example.sh
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test build Docker image
        run: |
          docker pull ${REGISTRY}/${IMAGE_NAME} || true
          ./builder.sh build-docker-image --skip-sudo
      - name: test build OpenWrt image
        env:
          OPENWRT_VERSION: v19.07.7
        run: |
          mkdir -p workdir
          ./builder.sh run -o workdir --skip-sudo\
                  --docker-opts "-v=$(pwd)/example:/workdir/example"\
                  -- sh -c "./example/example.sh example/config-rpi3"
