name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    env:
      REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        run: shellcheck builder.sh example/example.sh
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test build Docker image
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}
        run: |
          docker pull ${IMAGE_NAME} || true
          DOCKER_OPTS="--cache-from ${IMAGE_NAME}:latest"
          ./builder.sh build-docker-image --skip-sudo --docker-opts "$DOCKER_OPTS"
      - name: test build OpenWrt image
        env:
          OPENWRT_VERSION: "v21.02.0-rc4"
        run: |
          mkdir -p workdir
          ./builder.sh run -o workdir --skip-sudo\
                  -o workdir\
                  --docker-opts "-v=$(pwd)/example:/workdir/example"\
                  --docker-opts "-e=OPENWRT_VERSION=${OPENWRT_VERSION}" \
                  -- sh -c "./example/example.sh example/config-rpi3"
      - uses: actions/upload-artifact@v2
        with:
          name: example image
          path: workdir/lede/bin/targets
